# fly.toml app configuration file generated for esnow-fsopen-phonebook on 2023-09-04T11:31:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "esnow-fsopen-phonebook"
primary_region = "sjc"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
